name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PY_COLORS: 1
  UV_VERSION: 0.8.10
  UV_LOCKED: 1
  UV_NO_SYNC: 1

jobs:
  ci:
    runs-on: "${{ matrix.platform }}-latest"
    strategy:
      fail-fast: false
      # https://blog.jaraco.com/efficient-use-of-ci-resources/
      matrix:
        python: ["3.9", "3.13"]
        platform: ["ubuntu", "macos", "windows"]
        include:
        - python: "3.10"
          platform: "ubuntu"
        - python: "3.11"
          platform: "ubuntu"
        - python: "3.12"
          platform: "ubuntu"
    env:
      UV_PYTHON: ${{ matrix.python }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
    - name: Setup uv
      uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1  # v6.5.0
      with:
        version: ${{ env.UV_VERSION }}
    - name: Environment
      id: sync
      run: uv sync
    - name: taplo (TOML formatting)
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' && matrix.platform == 'ubuntu' }}
      run: uv run taplo fmt --check --diff pyproject.toml
    - name: ruff format
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run ruff format --diff --preview
    - name: ruff lint
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run ruff check --output-format github
    - name: pytest
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run pytest -vv
    - name: pyright
      if: ${{ !cancelled() && steps.sync.conclusion == 'success' }}
      run: uv run pyright src
